apps/calculator/urls.py
from django.urls import path
from .views import CalculatorView, MainCalculatorView, SignUpView, DiagnosticoListView

app_name = "calculator"

urlpatterns = [
    path('', CalculatorView.as_view(), name="home"),
    path('home/', MainCalculatorView.as_view(), name="index"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('diagnosticos/', DiagnosticoListView.as_view(), name="diagnosticos"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.calculator.urls', namespace='calculator'))
]

apps/calculator/models.py
from email.policy import default
from random import choices
from django.db import models
from django.contrib.auth.models import User

# Modelo de diagnostico de un usuario
# TODO: Falta realizar la relacion entre un user y el diagnostico

class Diagnostico(models.Model):
    LOW_WEIGHT = 'Bajo peso'
    NORMAL_WEIGHT = 'Peso normal'
    OVERWEIGHT = 'Sobrepeso'
    OBESITY = 'Obesidad'

    estadoPeso = [
        (LOW_WEIGHT, 'Bajo peso'),
        (NORMAL_WEIGHT, 'Peso normal'),
        (OVERWEIGHT, 'Sobrepeso'),
        (OBESITY, 'Obesidad'),
    ]

    fecha_diagnostico = models.DateField(auto_now_add=True, blank=True)
    estatura = models.FloatField(blank=False, null=False)
    peso = models.FloatField(blank=False, null=False)
    imc = models.FloatField(blank=True, null=False)
    estado = models.CharField(
        max_length=15, choices=estadoPeso, blank=True, null=False)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    # Funcion para calcular el imc
    def calc_imc(self):
        self.imc = self.peso / ((self.estatura)**2)
        self.imc = round(self.imc, 2)

    # Funcion para comparar el IMC y asignar peso
    def compare_imc(self):
        if 0 <= self.imc < 18.5:
            self.estado = self.LOW_WEIGHT
        elif 18.5 <= self.imc <= 24.9:
            self.estado = self.NORMAL_WEIGHT
        elif 25.0 <= self.imc <= 29.9:
            self.estado = self.OVERWEIGHT
        else:
            self.estado = self.OBESITY

    def save(self, *args, **kwargs):
        self.calc_imc()
        self.compare_imc()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-id']

apps/calculator/forms.py
from django import forms
from django.forms import ModelForm
from .models import Diagnostico
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# Make a form for the calculator

class CalcForm(ModelForm):
    class Meta:
        model = Diagnostico
        fields = ('estatura', 'peso')
        help_texts = {
            'estatura': _('Ingresa tu estatura en metros.'),
            'peso': _('Ingresa tu peso en kilogramos.'),
        }
        
class CustomUserForm(UserCreationForm):
    pass

apps/calculator/views.py
import json
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.core import serializers
from .forms import CalcForm, CustomUserForm
from .models import Diagnostico
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin


# Vistas para el calculo del IMC y almacenamiento en la base de datos
class CalculatorView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = CalcForm()
        context = {
            'form': form
        }
        return render(request, 'calculadora/calcSend.html', context)

    def post(self, request, *args, **kwargs):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            data = json.loads(request.body)
            imc = Diagnostico.objects.create(
                estatura=float(data['estatura']),
                peso=float(data['peso'])
            )
            data = serializers.serialize('json', [imc, ])
            imc.owner = request.user
            imc.save()
            return JsonResponse({'imc': imc.imc, 'imc_class': imc.estado}, status=200)
        return JsonResponse({"error": "Not a valid request"}, status=400)


class MainCalculatorView(View):
    def get(self, request, *args, **kwargs):
        form = CalcForm()
        context = {
            'form': form
        }
        return render(request, 'calculadora/localCalculator.html', context)

# Vistas para visualizar los datos de la base de datos

class DiagnosticoListView(LoginRequiredMixin, ListView):
    model = Diagnostico
    template_name = 'calculadora/diagnostico_list.html'
    context_object_name = 'diagnosticos'
    paginate_by = 5

    def get_queryset(self):
        return Diagnostico.objects.filter(owner=self.request.user).order_by('-id')

# Vistas de login y registro de usuarios


class SignUpView(View):
    def get(self, request, *args, **kwargs):
        form = CustomUserForm()
        context = {
            'form': form
        }
        return render(request, 'registration/signup.html', context)

    def post(self, request, *args, **kwargs):
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, user)
            return redirect(to='calculator:home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HL: {% block title %} {% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block css %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success p-3">
      <div class="container-fluid">
        <a class="navbar-brand font-weight-bold" 
        {% if user.is_authenticated %}
          href="{% url 'calculator:home' %}"
        {% else %}
          href="{% url 'calculator:index' %}"
          {% endif %}
          >Healthy Life</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          {% with request.resolver_match.url_name as url_name %}
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a
                class="nav-link mx-2
                {% if url_name == 'home' %}active{% endif %}
                {% if url_name == 'index' %}active{% endif %}"
                aria-current="page"
                {% if user.is_authenticated %}
                  href="{% url 'calculator:home' %}"
                {% else %}
                  href="{% url 'calculator:index' %}"
                {% endif %}
                >Inicio</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link mx-2 {% if url_name == 'diagnosticos' %}active{% endif %}" href="{% url 'calculator:diagnosticos' %}">Historial</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" href="{% url 'logout' %}">Cerrar Sesion</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link mx-2" href="{% url 'login' %}">Iniciar Sesion</a>
            </li>
            {% endif %}
          </ul>
          {% endwith %}
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/calculadora/calcSend.html
{% extends 'calculator.html' %}
{% load static %}
{% block js %}
    <script src="{% static 'js/sendFormHandler.js' %}"></script>
{% endblock %}

templates/calculadora/diagnostico_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
Historial de consultas
{% endblock %} 
{% block content %}
<div class="container mt-md-5 mt-5">
    <h3>Historial de diagnosticos:</h3>
    <div class="table-responsive mt-4 mx-auto">
        <table class="table table-hover shadow-sm rounded align-middle">
          <thead>
              <tr class="table-success">
                  <th scope="col">#</th>
                  <th scope="col">Fecha</th>
                  <th scope="col">Peso</th>
                  <th scope="col">IMC</th>
                  <th scope="col">Estado</th>
                </tr>
          </thead>
          <tbody>
            {% for diagnostico in diagnosticos %}
            <tr class="table-light">
                <th scope="row">{{diagnostico.id}}</th>
                <td>{{diagnostico.fecha_diagnostico|date}}</td>
                <td>{{ diagnostico.peso }}</td>
                <td>{{ diagnostico.imc }}</td>
                <td>{{ diagnostico.estado }}</td>
              </tr>
            {% empty %}
            <h5>No se han encontrado diagnosticos</h5>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
          </li>
            {% endif %}
          <li class="page-item disabled"><a class="page-link" href="#">Pagina: {{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <br>
</div>
{% endblock %}

templates/calculadora/localCalculator.html
{% extends 'calculator.html' %}
{% load static %}
{% block js %}
    <script src="{% static 'js/calculateIMC.js' %}"></script>
{% endblock %}

templates/calculator.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Calculadora IMC {% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container montserrat mt-5 row mx-auto">
        <div class="col-12 col-md-4 offset-md-1 mt-md-4 bg-white p-4 shadow-lg rounded-4">
            <form id="calc_form" method="POST">
                <div class="mb-4 text-center">
                    <h3>Calculadora IMC</h3>
                </div>
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-md btn-block btn-primary">Calcular</button>
                </div>
            </form>
        </div>
        <div class="col-12 col-md-4 mt-4 mb-md-0 mb-4 p-4 bg-white rounded-4 shadow-lg offset-md-1">
            <div class="d-flex flex-column ">
                <div class="text-center">
                    <h3>Resultados</h3>
                </div>
                <div class="mt-4 ms-2 mt-md-5">
                    <p>
                        <span class="fw-bold">
                            Estatura ingresada:
                        </span>
                        <span id="result-estatura">
                            Sin resultados
                        </span>
                    </p>
                </div>
                <div class="mt-2 ms-2">
                    <p>
                        <span class="fw-bold">
                            Peso ingresado:
                        </span>
                        <span id="result-peso">
                            Sin resultados
                        </span>
                    </p>
                </div>
                <div class="mt-2 ms-2">
                    <p>
                        <span class="fw-bold">
                            IMC:
                        </span>
                        <span id="result-imc">
                            Sin resultados
                        </span>
                    </p>
                </div>
                <div class="mt-2 ms-2"><p>
                    <span class="fw-bold">
                        Estado:
                    </span>
                    <span id="result-imc-class">
                        Sin resultados
                    </span>
                </p></div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
{% endblock %}